create extension if not exists "hypopg" with schema "extensions";

create extension if not exists "index_advisor" with schema "extensions";

drop extension if exists "pg_net";


  create table "public"."bible_verses" (
    "id" uuid not null default gen_random_uuid(),
    "reference" text not null,
    "verse_text" text not null,
    "translation" text default 'NET'::text
      );


alter table "public"."bible_verses" enable row level security;


  create table "public"."daily_messages" (
    "id" bigint generated by default as identity not null,
    "message" text,
    "verse_reference" text,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "message_date" date,
    "message_text" text,
    "verse_query" text,
    "background_key" text,
    "message_index" integer,
    "is_primary" boolean not null default false
      );


alter table "public"."daily_messages" enable row level security;


  create table "public"."entries" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "type" text not null,
    "content" text not null,
    "status" text not null default 'active'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "answered_at" timestamp with time zone,
    "answer_notes" text,
    "reminder_frequency" text not null default 'none'::text,
    "reminder_time" time without time zone,
    "last_reminded_at" timestamp with time zone,
    "title" text,
    "reminder_group_id" uuid,
    "completed_from_label" text
      );


alter table "public"."entries" enable row level security;


  create table "public"."message_feedback" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "message_id" bigint not null,
    "feedback_type" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."message_feedback" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "timezone" text default 'America/New_York'::text,
    "notifications_enabled" boolean not null default true,
    "morning_notification_time" time without time zone default '07:00:00'::time without time zone,
    "evening_reminder_time" time without time zone default '20:30:00'::time without time zone
      );


alter table "public"."profiles" enable row level security;


  create table "public"."reminder_groups" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "name" text not null,
    "cadence" text not null,
    "time_of_day" time without time zone,
    "day_of_week" integer,
    "day_of_month" integer,
    "month_of_year" integer,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "next_run_at" timestamp with time zone,
    "last_run_at" timestamp with time zone
      );


alter table "public"."reminder_groups" enable row level security;

CREATE UNIQUE INDEX bible_verses_pkey ON public.bible_verses USING btree (id);

CREATE UNIQUE INDEX bible_verses_reference_unique ON public.bible_verses USING btree (reference);

CREATE UNIQUE INDEX daily_messages_pkey ON public.daily_messages USING btree (id);

CREATE UNIQUE INDEX daily_messages_user_id_message_date_key ON public.daily_messages USING btree (user_id, message_date);

CREATE UNIQUE INDEX entries_pkey ON public.entries USING btree (id);

CREATE INDEX entries_reminder_group_id_idx ON public.entries USING btree (reminder_group_id);

CREATE INDEX entries_user_id_idx ON public.entries USING btree (user_id);

CREATE INDEX entries_user_status_idx ON public.entries USING btree (user_id, status);

CREATE INDEX entries_user_type_idx ON public.entries USING btree (user_id, type);

CREATE UNIQUE INDEX message_feedback_pkey ON public.message_feedback USING btree (id);

CREATE UNIQUE INDEX one_feedback_per_type_per_message ON public.message_feedback USING btree (user_id, message_id, feedback_type);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX reminder_groups_pkey ON public.reminder_groups USING btree (id);

CREATE INDEX reminder_groups_user_cadence_idx ON public.reminder_groups USING btree (user_id, cadence);

CREATE INDEX reminder_groups_user_id_idx ON public.reminder_groups USING btree (user_id);

alter table "public"."bible_verses" add constraint "bible_verses_pkey" PRIMARY KEY using index "bible_verses_pkey";

alter table "public"."daily_messages" add constraint "daily_messages_pkey" PRIMARY KEY using index "daily_messages_pkey";

alter table "public"."entries" add constraint "entries_pkey" PRIMARY KEY using index "entries_pkey";

alter table "public"."message_feedback" add constraint "message_feedback_pkey" PRIMARY KEY using index "message_feedback_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."reminder_groups" add constraint "reminder_groups_pkey" PRIMARY KEY using index "reminder_groups_pkey";

alter table "public"."bible_verses" add constraint "bible_verses_reference_unique" UNIQUE using index "bible_verses_reference_unique";

alter table "public"."daily_messages" add constraint "daily_messages_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."daily_messages" validate constraint "daily_messages_user_id_fkey";

alter table "public"."entries" add constraint "entries_reminder_frequency_check" CHECK ((reminder_frequency = ANY (ARRAY['none'::text, 'daily'::text, 'weekly'::text, 'biweekly'::text, 'monthly'::text]))) not valid;

alter table "public"."entries" validate constraint "entries_reminder_frequency_check";

alter table "public"."entries" add constraint "entries_reminder_group_id_fkey" FOREIGN KEY (reminder_group_id) REFERENCES public.reminder_groups(id) ON DELETE SET NULL not valid;

alter table "public"."entries" validate constraint "entries_reminder_group_id_fkey";

alter table "public"."entries" add constraint "entries_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'answered'::text]))) not valid;

alter table "public"."entries" validate constraint "entries_status_check";

alter table "public"."entries" add constraint "entries_type_check" CHECK ((type = ANY (ARRAY['prayer'::text, 'gratitude'::text, 'affirmation'::text, 'goal'::text]))) not valid;

alter table "public"."entries" validate constraint "entries_type_check";

alter table "public"."entries" add constraint "entries_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."entries" validate constraint "entries_user_id_fkey";

alter table "public"."message_feedback" add constraint "message_feedback_feedback_type_check" CHECK ((feedback_type = ANY (ARRAY['helpful'::text, 'not_helpful'::text, 'favorite'::text]))) not valid;

alter table "public"."message_feedback" validate constraint "message_feedback_feedback_type_check";

alter table "public"."message_feedback" add constraint "message_feedback_message_id_fkey" FOREIGN KEY (message_id) REFERENCES public.daily_messages(id) ON DELETE CASCADE not valid;

alter table "public"."message_feedback" validate constraint "message_feedback_message_id_fkey";

alter table "public"."message_feedback" add constraint "message_feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."message_feedback" validate constraint "message_feedback_user_id_fkey";

alter table "public"."message_feedback" add constraint "one_feedback_per_type_per_message" UNIQUE using index "one_feedback_per_type_per_message";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."reminder_groups" add constraint "reminder_groups_cadence_check" CHECK ((cadence = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'yearly'::text, 'custom'::text]))) not valid;

alter table "public"."reminder_groups" validate constraint "reminder_groups_cadence_check";

alter table "public"."reminder_groups" add constraint "reminder_groups_day_of_month_check" CHECK (((day_of_month IS NULL) OR ((day_of_month >= 1) AND (day_of_month <= 31)))) not valid;

alter table "public"."reminder_groups" validate constraint "reminder_groups_day_of_month_check";

alter table "public"."reminder_groups" add constraint "reminder_groups_day_of_week_check" CHECK (((day_of_week IS NULL) OR ((day_of_week >= 0) AND (day_of_week <= 6)))) not valid;

alter table "public"."reminder_groups" validate constraint "reminder_groups_day_of_week_check";

alter table "public"."reminder_groups" add constraint "reminder_groups_month_of_year_check" CHECK (((month_of_year IS NULL) OR ((month_of_year >= 1) AND (month_of_year <= 12)))) not valid;

alter table "public"."reminder_groups" validate constraint "reminder_groups_month_of_year_check";

alter table "public"."reminder_groups" add constraint "reminder_groups_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."reminder_groups" validate constraint "reminder_groups_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.compute_reminder_group_next_run(p_cadence text, p_time_of_day time without time zone, p_day_of_week integer, p_day_of_month integer, p_month_of_year integer, p_now timestamp with time zone DEFAULT now())
 RETURNS timestamp with time zone
 LANGUAGE plpgsql
AS $function$
declare
  local_now timestamp;
  candidate timestamp;
  target_time time;
  current_date_local date;
  days_ahead integer;
  target_year integer;
  target_month integer;
  safe_day integer;
  last_day integer;
begin
  if p_time_of_day is null then
    target_time := time '09:00';
  else
    target_time := p_time_of_day;
  end if;

  local_now := p_now::timestamp;
  current_date_local := local_now::date;

  if p_cadence = 'daily' then
    candidate := current_date_local + target_time;

    if candidate <= local_now then
      candidate := (current_date_local + 1) + target_time;
    end if;

    return candidate;
  end if;

  if p_cadence = 'weekly' then
    if p_day_of_week is null then
      return null;
    end if;

    days_ahead := p_day_of_week - extract(dow from current_date_local)::integer;

    if days_ahead < 0 then
      days_ahead := days_ahead + 7;
    end if;

    candidate := (current_date_local + days_ahead) + target_time;

    if candidate <= local_now then
      candidate := (current_date_local + days_ahead + 7) + target_time;
    end if;

    return candidate;
  end if;

  if p_cadence = 'monthly' then
    if p_day_of_month is null then
      return null;
    end if;

    target_year := extract(year from current_date_local)::integer;
    target_month := extract(month from current_date_local)::integer;

    last_day := extract(day from (date_trunc('month', make_date(target_year, target_month, 1)) + interval '1 month - 1 day'))::integer;
    safe_day := least(p_day_of_month, last_day);

    candidate := make_date(target_year, target_month, safe_day) + target_time;

    if candidate <= local_now then
      if target_month = 12 then
        target_year := target_year + 1;
        target_month := 1;
      else
        target_month := target_month + 1;
      end if;

      last_day := extract(day from (date_trunc('month', make_date(target_year, target_month, 1)) + interval '1 month - 1 day'))::integer;
      safe_day := least(p_day_of_month, last_day);

      candidate := make_date(target_year, target_month, safe_day) + target_time;
    end if;

    return candidate;
  end if;

  if p_cadence = 'yearly' then
    if p_day_of_month is null or p_month_of_year is null then
      return null;
    end if;

    target_year := extract(year from current_date_local)::integer;

    last_day := extract(day from (date_trunc('month', make_date(target_year, p_month_of_year, 1)) + interval '1 month - 1 day'))::integer;
    safe_day := least(p_day_of_month, last_day);

    candidate := make_date(target_year, p_month_of_year, safe_day) + target_time;

    if candidate <= local_now then
      target_year := target_year + 1;

      last_day := extract(day from (date_trunc('month', make_date(target_year, p_month_of_year, 1)) + interval '1 month - 1 day'))::integer;
      safe_day := least(p_day_of_month, last_day);

      candidate := make_date(target_year, p_month_of_year, safe_day) + target_time;
    end if;

    return candidate;
  end if;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_reminder_group_next_run()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  current_local timestamp;
  candidate_local timestamp;
  target_date date;
  target_day integer;
  last_day integer;
  target_month integer;
  target_year integer;
begin
  if new.is_active = false then
    new.next_run_at := null;
    return new;
  end if;

  if new.time_of_day is null then
    new.next_run_at := null;
    return new;
  end if;

  current_local := now();

  if new.cadence = 'daily' then
    candidate_local := date_trunc('day', current_local) + new.time_of_day;

    if candidate_local <= current_local then
      candidate_local := candidate_local + interval '1 day';
    end if;

    new.next_run_at := candidate_local;
    return new;
  end if;

  if new.cadence = 'weekly' then
    if new.day_of_week is null then
      new.next_run_at := null;
      return new;
    end if;

    target_date :=
      current_date
      + ((new.day_of_week - extract(dow from current_date)::integer + 7) % 7);

    candidate_local := target_date + new.time_of_day;

    if candidate_local <= current_local then
      candidate_local := candidate_local + interval '7 days';
    end if;

    new.next_run_at := candidate_local;
    return new;
  end if;

  if new.cadence = 'monthly' then
    if new.day_of_month is null then
      new.next_run_at := null;
      return new;
    end if;

    target_date := date_trunc('month', current_date)::date;
    last_day := extract(day from (target_date + interval '1 month - 1 day'))::integer;
    target_day := least(new.day_of_month, last_day);

    candidate_local := (target_date + (target_day - 1)) + new.time_of_day;

    if candidate_local <= current_local then
      target_date := (date_trunc('month', current_date) + interval '1 month')::date;
      last_day := extract(day from (target_date + interval '1 month - 1 day'))::integer;
      target_day := least(new.day_of_month, last_day);
      candidate_local := (target_date + (target_day - 1)) + new.time_of_day;
    end if;

    new.next_run_at := candidate_local;
    return new;
  end if;

  if new.cadence = 'yearly' then
    if new.month_of_year is null or new.day_of_month is null then
      new.next_run_at := null;
      return new;
    end if;

    target_month := new.month_of_year;
    target_year := extract(year from current_date)::integer;

    target_date := make_date(target_year, target_month, 1);
    last_day := extract(day from (target_date + interval '1 month - 1 day'))::integer;
    target_day := least(new.day_of_month, last_day);

    candidate_local := (target_date + (target_day - 1)) + new.time_of_day;

    if candidate_local <= current_local then
      target_year := target_year + 1;
      target_date := make_date(target_year, target_month, 1);
      last_day := extract(day from (target_date + interval '1 month - 1 day'))::integer;
      target_day := least(new.day_of_month, last_day);
      candidate_local := (target_date + (target_day - 1)) + new.time_of_day;
    end if;

    new.next_run_at := candidate_local;
    return new;
  end if;

  new.next_run_at := null;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "public"."bible_verses" to "anon";

grant insert on table "public"."bible_verses" to "anon";

grant references on table "public"."bible_verses" to "anon";

grant select on table "public"."bible_verses" to "anon";

grant trigger on table "public"."bible_verses" to "anon";

grant truncate on table "public"."bible_verses" to "anon";

grant update on table "public"."bible_verses" to "anon";

grant delete on table "public"."bible_verses" to "authenticated";

grant insert on table "public"."bible_verses" to "authenticated";

grant references on table "public"."bible_verses" to "authenticated";

grant select on table "public"."bible_verses" to "authenticated";

grant trigger on table "public"."bible_verses" to "authenticated";

grant truncate on table "public"."bible_verses" to "authenticated";

grant update on table "public"."bible_verses" to "authenticated";

grant delete on table "public"."bible_verses" to "service_role";

grant insert on table "public"."bible_verses" to "service_role";

grant references on table "public"."bible_verses" to "service_role";

grant select on table "public"."bible_verses" to "service_role";

grant trigger on table "public"."bible_verses" to "service_role";

grant truncate on table "public"."bible_verses" to "service_role";

grant update on table "public"."bible_verses" to "service_role";

grant delete on table "public"."daily_messages" to "anon";

grant insert on table "public"."daily_messages" to "anon";

grant references on table "public"."daily_messages" to "anon";

grant select on table "public"."daily_messages" to "anon";

grant trigger on table "public"."daily_messages" to "anon";

grant truncate on table "public"."daily_messages" to "anon";

grant update on table "public"."daily_messages" to "anon";

grant delete on table "public"."daily_messages" to "authenticated";

grant insert on table "public"."daily_messages" to "authenticated";

grant references on table "public"."daily_messages" to "authenticated";

grant select on table "public"."daily_messages" to "authenticated";

grant trigger on table "public"."daily_messages" to "authenticated";

grant truncate on table "public"."daily_messages" to "authenticated";

grant update on table "public"."daily_messages" to "authenticated";

grant delete on table "public"."daily_messages" to "service_role";

grant insert on table "public"."daily_messages" to "service_role";

grant references on table "public"."daily_messages" to "service_role";

grant select on table "public"."daily_messages" to "service_role";

grant trigger on table "public"."daily_messages" to "service_role";

grant truncate on table "public"."daily_messages" to "service_role";

grant update on table "public"."daily_messages" to "service_role";

grant delete on table "public"."entries" to "anon";

grant insert on table "public"."entries" to "anon";

grant references on table "public"."entries" to "anon";

grant select on table "public"."entries" to "anon";

grant trigger on table "public"."entries" to "anon";

grant truncate on table "public"."entries" to "anon";

grant update on table "public"."entries" to "anon";

grant delete on table "public"."entries" to "authenticated";

grant insert on table "public"."entries" to "authenticated";

grant references on table "public"."entries" to "authenticated";

grant select on table "public"."entries" to "authenticated";

grant trigger on table "public"."entries" to "authenticated";

grant truncate on table "public"."entries" to "authenticated";

grant update on table "public"."entries" to "authenticated";

grant delete on table "public"."entries" to "service_role";

grant insert on table "public"."entries" to "service_role";

grant references on table "public"."entries" to "service_role";

grant select on table "public"."entries" to "service_role";

grant trigger on table "public"."entries" to "service_role";

grant truncate on table "public"."entries" to "service_role";

grant update on table "public"."entries" to "service_role";

grant delete on table "public"."message_feedback" to "anon";

grant insert on table "public"."message_feedback" to "anon";

grant references on table "public"."message_feedback" to "anon";

grant select on table "public"."message_feedback" to "anon";

grant trigger on table "public"."message_feedback" to "anon";

grant truncate on table "public"."message_feedback" to "anon";

grant update on table "public"."message_feedback" to "anon";

grant delete on table "public"."message_feedback" to "authenticated";

grant insert on table "public"."message_feedback" to "authenticated";

grant references on table "public"."message_feedback" to "authenticated";

grant select on table "public"."message_feedback" to "authenticated";

grant trigger on table "public"."message_feedback" to "authenticated";

grant truncate on table "public"."message_feedback" to "authenticated";

grant update on table "public"."message_feedback" to "authenticated";

grant delete on table "public"."message_feedback" to "service_role";

grant insert on table "public"."message_feedback" to "service_role";

grant references on table "public"."message_feedback" to "service_role";

grant select on table "public"."message_feedback" to "service_role";

grant trigger on table "public"."message_feedback" to "service_role";

grant truncate on table "public"."message_feedback" to "service_role";

grant update on table "public"."message_feedback" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."reminder_groups" to "anon";

grant insert on table "public"."reminder_groups" to "anon";

grant references on table "public"."reminder_groups" to "anon";

grant select on table "public"."reminder_groups" to "anon";

grant trigger on table "public"."reminder_groups" to "anon";

grant truncate on table "public"."reminder_groups" to "anon";

grant update on table "public"."reminder_groups" to "anon";

grant delete on table "public"."reminder_groups" to "authenticated";

grant insert on table "public"."reminder_groups" to "authenticated";

grant references on table "public"."reminder_groups" to "authenticated";

grant select on table "public"."reminder_groups" to "authenticated";

grant trigger on table "public"."reminder_groups" to "authenticated";

grant truncate on table "public"."reminder_groups" to "authenticated";

grant update on table "public"."reminder_groups" to "authenticated";

grant delete on table "public"."reminder_groups" to "service_role";

grant insert on table "public"."reminder_groups" to "service_role";

grant references on table "public"."reminder_groups" to "service_role";

grant select on table "public"."reminder_groups" to "service_role";

grant trigger on table "public"."reminder_groups" to "service_role";

grant truncate on table "public"."reminder_groups" to "service_role";

grant update on table "public"."reminder_groups" to "service_role";


  create policy "Verses are readable"
  on "public"."bible_verses"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert own daily messages"
  on "public"."daily_messages"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can view own daily messages"
  on "public"."daily_messages"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can delete own entries"
  on "public"."entries"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert own entries"
  on "public"."entries"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update own entries"
  on "public"."entries"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can view own entries"
  on "public"."entries"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can delete own feedback"
  on "public"."message_feedback"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert own feedback"
  on "public"."message_feedback"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update own feedback"
  on "public"."message_feedback"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can view own feedback"
  on "public"."message_feedback"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert own profile"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "Users can view own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Users can delete their own reminder groups"
  on "public"."reminder_groups"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert their own reminder groups"
  on "public"."reminder_groups"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own reminder groups"
  on "public"."reminder_groups"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own reminder groups"
  on "public"."reminder_groups"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));


CREATE TRIGGER set_entries_updated_at BEFORE UPDATE ON public.entries FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER reminder_groups_set_next_run BEFORE INSERT OR UPDATE ON public.reminder_groups FOR EACH ROW EXECUTE FUNCTION public.set_reminder_group_next_run();

CREATE TRIGGER set_reminder_groups_updated_at BEFORE UPDATE ON public.reminder_groups FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


